'use strict';

module.exports = {
  extends: [
    'eslint:recommended',
    'prettier',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:node/recommended',
    'plugin:jsdoc/recommended',
  ],
  plugins: ['jsdoc'],
  env: {
    es6: true,
    node: true,
    jest: true,
  },
  globals: {
    strapi: false,
  },
  rules: {
    indent: ['error', 2, { SwitchCase: 1 }],
    'linebreak-style': ['error', 'unix'],
    'no-console': 'error',
    quotes: ['error', 'single'],
    semi: ['error', 'always'],
    'object-curly-spacing': ['error', 'always'],
    'prefer-const': 'error',
    'no-var': 'error',
    'dot-notation': 'error',
    eqeqeq: 'error',
    'no-multi-spaces': 'error',
    'prefer-regex-literals': 'error',
    'prefer-promise-reject-errors': 'error',
    'array-bracket-newline': ['error', 'consistent'],
    'block-spacing': 'error',
    'brace-style': 'error',
    'comma-dangle': ['error', 'always-multiline'],
    'arrow-parens': ['error', 'always'],
    'quote-props': ['error', 'as-needed'],
    'no-trailing-spaces': 'error',
    'jsdoc/require-hyphen-before-param-description': ['error'],
    // Strapi eslint rules:
    'jsdoc/require-jsdoc': [
      'warn',
      {
        publicOnly: true,
        require: {
          ArrowFunctionExpression: true,
          ClassDeclaration: true,
          ClassExpression: true,
          FunctionDeclaration: true,
          FunctionExpression: true,
          MethodDefinition: true,
        },
      },
    ],
    'require-atomic-updates': 'off',
    'no-process-exit': 'off',
    strict: ['error', 'global'],
    'import/order': 'error',
    'import/no-cycle': 'error',
    'import/no-useless-path-segments': 'error',
    'import/first': 'error',
    'import/extensions': ['error', 'never'],
    'import/newline-after-import': 'error',
    'node/exports-style': ['error', 'module.exports'],
    'node/no-extraneous-require': ['error', { allowModules: ['supertest'] }],
    'node/no-new-require': 'error',
    'node/no-path-concat': 'error',
    'node/no-callback-literal': 'error',
    'node/no-unpublished-require': ['error', { allowModules: ['supertest', '@strapi/strapi'] }],
    'node/handle-callback-err': 'error',
    'one-var': ['error', 'never'],
  },
};
